# Generated by Django 4.2.7 on 2023-12-03 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consesionario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='moldelo',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='sucursal',
        ),
    ]
