# Generated by Django 4.2.7 on 2023-12-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consesionario', '0002_rename_moldelo_auto_modelo_remove_auto_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
